"""Ink-and-ochre page palette and distinct model colours for statistical plots."""
from pathlib import Path

INK = '#292929'
HEADING = '#252525'
PRIMARY = '#353535'
OCHRE = '#AF8538'
MUTED = '#73716C'
AXIS = '#65635E'
GRID = '#E8E6E1'
NEUTRAL = '#DAD8D3'
MATRIX_ZERO = '#E6E4DE'
PAPER = '#FFFFFF'
PANEL_TITLE = '#F1F0ED'
RESULT = '#FFFCF6'
RESULT_TITLE = '#F4ECD9'
MOLS = ['#F5F4F1', '#E0DEDA', '#BBB8B1']

# Model hue and marker are consistent across every statistical plot.
# Effort uses shade and line pattern; Qwen3.5 sizes have distinct triangle markers.
MODEL_COLORS = {
    'qwen4': '#7BA864', 'qwen9': '#488952', 'qwen35': '#1F6541',
    'qwen38': '#9162A8', 'luna_medium': '#CE9650', 'luna_high': '#AD681F',
    'deepseek_low': '#878787', 'deepseek_high': '#505050', 'fable': '#AD4055', 'fable_high': '#70283C',
    'astra_medium': '#4B90AD', 'astra_high': '#2359A0',
}
OPUS_COLOR = '#856B3E'


def write_tex():
    colors = {
        'paperink': HEADING, 'paperaccent': OCHRE, 'papermuted': MUTED,
        'paperline': NEUTRAL, 'paperwhite': PAPER, 'paperwarmgray': PANEL_TITLE,
        'paperresult': RESULT, 'paperresulttitle': RESULT_TITLE,
    }
    lines = ['% Generated by visual_theme.py; shared manuscript palette.']
    lines += [rf'\definecolor{{{name}}}{{HTML}}{{{value[1:]}}}' for name, value in colors.items()]
    Path(__file__).with_suffix('.tex').write_text('\n'.join(lines) + '\n')


if __name__ == '__main__':
    write_tex()
